### ISSUE TITLE
Ontwerp Feedback

### ISSUE THREAD

**Issue by amirnapoletano** [Robin1224/visual-thinking#33]
![Image](https://github.com/user-attachments/assets/e5a8dcdc-a166-4073-9fac-d6c4b12dfa58)

**Comment by amirnapoletano** [comment]
https://www.figma.com/design/zM7mZ71HH7qQP1xO2KctIJ/Visual-Thinking---Designs?node-id=1-319&t=AmnCdPsuO8B3G2tl-1

**Comment by Mossati** [comment]
### Feedback
De artikelen zijn te druk het is moeilijk om een duidelijk overzicht te hebben, probeer wat onderscheid te maken door een border te gebruiken of meer witruimte tussen de artikelen.

het gedeelte met "wil je zelf een tekenmethode toevoegen" moet boven geplaatst worden want nu moet je helemaal naar beneden scrollen om het te zien en als je niet naar beneden scrollt weet je niet eens of die optie bestaat.

**Comment by rutgerkock** [comment]
Het is voor mij zelfs met de duur/niveau uitleg rechtsboven onduidelijk wat de icoontjes rechtsonder elk blok betekenen. Ik zou of duidelijkere icoontjes ontwerpen of het gewoon uitschrijven, net zoals de gele blokken, die zijn erg duidelijk. Ook zit er geen scheiding tussen het blok met de categorieen en de blokken van de tekeningen (?) zelf, ik zou om duidelijk te maken wat waarbij hoort een scheiding maken.

**Comment by driezie** [comment]
Het ontwerp ziet er super goed uit!

Ik vind alleen die blauwe lijn in de header echt niet mooi. Je had dit beter zonder die blauwe achtergrond kunnen doen, en de knop in de content kunnen plaatsen met bijvoorbeeld een pijltje terug of een huisicoon voor de homepage.

Ik weet namelijk niet of dit een link is of alleen een breadcrumb.
